[project]
name = "nrk-tvers-solver"
version = "0.1.0"
description = "Solver for NRK Tvers game"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asgi-lifespan>=2.1.0",
    "asgiref>=3.8.1",
    "flask>=3.1.0",
    "uvicorn>=0.34.0",
]
